config/routes.rb
Posfis::Application.routes.draw do
  
  namespace :manage do
    resources :friends do
      member do
        get 'add_friend'
      end
    end
    resources :products do
      collection do
        get 'dealerInfo'
      end
    end
    resources :blogs
    resources :trades do
      collection do
        get 'history'
      end
    end
    resources :orders do
      collection do
        get 'history'
      end
      member do
        get 'next_phase'
      end
    end
    resources :settings
    resources :user_settings
    resources :product_value
    resources :dealer_info
  end

  namespace :admin do
    resources :users
    resources :logs
  end

  root 'tops#index'

  devise_for :users, :controllers => { :registrations => :registrations }

  

  resources :tops
  resources :blogs

  resources :market do
    member do
      get 'purchase'
      post 'confirm'
      post 'checkout'
      get 'success'
      post 'complete'
      get 'dealer_info'
    end
  end

  namespace :manage do
  end
  resources :manage do
    collection do
      post 'create_blog'
    end
  end
end

app/controllers/market_controller.rb
class MarketController < ApplicationController
	layout 'market'
	include ActiveMerchant::Billing
	before_action :set_params, only: [:dealer_info, :purchase, :confirm, :checkout]

	def dealer_info
		@dealer_info = AsctInfo.where(user_id: @product.id).first
		@user = User.find(@product.user_id)
		friends = Manage::Friend.select("to_user_id").where(:from_user_id => @product.user_id)
    @friends = Manage::Friend.where(:to_user_id => friends)
    @products = Manage::Product.where(:user_id => @product.user_id)
	end

	def purchase
		@market = Order.new
	end

	def confirm
		@confirm = Order.new(order_params)
	end

	def checkout
		@confirm = Order.new(order_params)
		price = @confirm.price.to_i * @confirm.request_count.to_i
		$order = @confirm
		setup_response = express_gateway.setup_purchase(price,
			:currency_code => :JPY,
	    :ip                => request.remote_ip,
	    :return_url        => url_for(:action => 'success', :only_path => false),
	    :cancel_return_url => url_for(:action => 'purchase', :only_path => false)
	  )
  redirect_to express_gateway.redirect_url_for(setup_response.token)
	end

	def success
		redirect_to :action => 'purchase' unless params[:token]
  
	  details_response = express_gateway.details_for(params[:token])
	  
	  if !details_response.success?
	    @message = details_response.message
	    render :action => 'error'
	    return
	  end
	    
	  @address = details_response.address
	end

	def complete
	  purchase = express_gateway.purchase(5000,
	  	:currency_code => :JPY,
	    :ip       => request.remote_ip,
	    :payer_id => params[:payer_id],
	    :token    => params[:token]
	  )
	  
	  if !purchase.success?
	    @message = purchase.message
	    render :action => 'error'
	    return
	  end
	  if user_signed_in?
	  	$order.buyer_user_id = current_user.id
	  else
	  	$order.buyer_user_id = 0
	  end
	  $order.condition = 0
	  $order.product.count = $order.product.count - 1
	  $order.save
	  @log = Log.new
	  @log.for_user_id = $order.buyer_user_id
	  @log.log_type = 3
	  @log.save

	  @log = Log.new
	  @log.for_user_id = $order.business_user_id
	  @log.log_type = 4
	  @log.save

	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_params
      @product = Manage::Product.find(params[:id])
    end

    def order_params
    	params.require(:order).permit(:business_user_id, :product_id, :request_count, :price, :name, :address_number, :address, :user_email, :user_tel)
    end

    def express_gateway
    	@express_product = Manage::Product.find(params[:id])
    	@express_user = User.find(@express_product.user_id)
    	@gateway ||= PaypalExpressGateway.new(
		    :login => @express_user.paypal_login,
		    :password => @express_user.paypal_password,
		    :signature => @express_user.paypal_signature
		  )
    end
end

app/helpers/market_helper.rb
module MarketHelper
end

app/views/market/complete.html.erb
<meta http-equiv="refresh" content="60; URL=http://www.example.com/">
<div class="market w2">
	<div class="confirm">
		<h1>ありがとうございます。</h1>
		<p>お支払いが完了しました。</p>
		<br>
		<p>約10秒後に自動でトップページへ移動します。</p>
	</div>
</div>

app/views/market/confirm.html.erb
<div class="market w2">
<div class="confirm">
	<h3><%= @product.product_name %>購入確認ページ</h3>
		<p>価格: <span class="price"><%= @product.price %></span>円</p>
		<p>送料: <span class="fee"><%= @product.delivery_fee %></span>円</p>
		<p>個数: <span class="count"><%= @confirm.request_count %></span>個</p>
		
		<p class="sum"></p>
	
		<label>お届け先名 :</label>
	  <%= @confirm.name %><br>
	  <label>お届け先郵便番号 :</label>
	  <%= @confirm.address_number %><br>
	  <label>お届け先 :</label>
	  <%= @confirm.address %><br>
	  <label>ご連絡先(email) :</label>
	  <%= @confirm.user_email %><br>
	  <label>ご連絡先(電話番号) :</label>
	  <%= @confirm.user_tel %><br>
	  <br>
	  <label>お支払い :</label><br>
    <%= form_for @confirm, :url => {:action => 'checkout'} do |f| %>
      <%= f.hidden_field :business_user_id_integer, :value => @product.user_id %>
      <%= f.hidden_field :product_id, :value => @product.id %>
      <%= f.hidden_field :request_count, :value => @confirm.request_count %>
      <%= f.hidden_field :price, :value => @product.price %>
      <%= f.hidden_field :name, :value => @confirm.name %>
      <%= f.hidden_field :address_number, :value => @confirm.address_number %>
      <%= f.hidden_field :address, :value => @confirm.address %>
      <%= f.hidden_field :user_email, :value => @confirm.user_email %>
      <%= f.hidden_field :user_tel, :value => @confirm.user_tel %>

      <%= image_submit_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif") %>

<% end %>
	</div>
</div>

<script>
	$(function(){
		var $price = parseInt( $(".price").html(), 10 );
		var $fee = parseInt( $(".fee").html(), 10 );
		var $count = parseInt( $(".count").html(), 10 );
		
		var $sum = $price*$count+$fee;
		
		
		$(".sum").html("合計 : "+$sum+"円(税込み)");
	})
</script>

app/views/market/dealer_info.html.erb
<div class="item w2">
	<div class="imgBox">
		<%= image_tag @user.avatar.url(:medium) %>
	</div>
	<nav>
		<div class="navBox">
			<ul>
				<li class="menu info c1">
					<a href="">
						<span class="icon icon-user"></span>
						<h2>情報</h2>
						<p>広島県広島市</p>
					</a>
				</li>
				<li class="menu goods c2">
					<span class="icon icon-bag"></span>
					<h2>販売</h2>
					<p><%= @products.count %>点</p>
				</li>
			</ul>
		</div>
		<div class="navBox">
			<ul>
				<li class="menu friends c3">
					<span class="icon icon-users"></span>
					<h2>友達</h2>
					<p><%= @friends.count %>人</p>
				</li>
				<li class="menu pictures c4">
					<span class="icon icon-picture"></span>
					<h2>写真</h2>
					<p>13枚</p>
				</li>
			</ul>
		</div>
	</nav>
</div>

<div class="item w3 c1">
	<div class="item-inner">
		<h2>特定商取引の表示</h2>
		<table>
			<tr>
				<th>販売業者</th>
				<td><%= @dealer_info.dealer %></td>
			</tr>
			<tr>
				<th>運営責任者</th>
				<td><%= @dealer_info.manager %></td>
			</tr>
			<tr>
				<th>郵便番号</th>
				<td><%= @dealer_info.manager_number %></td>
			</tr>
			<tr>
				<th>所在地</th>
				<td><%= @dealer_info.manager_address %></td>
			</tr>
			<tr>
				<th>電話番号</th>
				<td><%= @dealer_info.manager_tel %></td>
			</tr>
			<tr>
				<th>メールアドレス</th>
				<td><%= @dealer_info.manager_mail %></td>
			</tr>
			<tr>
				<th>商品代金以外の必要料金</th>
				<td><%= @dealer_info.additional_costs %></td>
			</tr>
			<tr>
				<th>注文方法</th>
				<td><%= @dealer_info.order_method %></td>
			</tr>
			<tr>
				<th>支払い方法</th>
				<td><%= @dealer_info.pay_method %></td>
			</tr>
			<tr>
				<th>支払い期限</th>
				<td><%= @dealer_info.pay_limit %></td>
			</tr>
			<tr>
				<th>引き渡し期間</th>
				<td><%= @dealer_info.delivered_time %></td>
			</tr>
			<tr>
				<th>返品交換について</th>
				<td><%= @dealer_info.return_method %></td>
			</tr>
		</table>
	</div>
</div>

app/views/market/error.html.erb
<meta http-equiv="refresh" content="5; URL=tops">
<h1>支払いを完了できませんでした。</h1>
<p>もう一度、最初からやり直してください。</p>
<br>
<p>約15秒後に自動でトップページへ移動します。</p>
<p>Unfortunately an error occurred: <%= @message %></p>

app/views/market/purchase.html.erb
<div class="market w2">
	<div class="quick">
		<h3><%= @product.product_name %>購入ページ</h3>
		<%= form_for(@market, :url => {:action => 'confirm'}) do |f| %>
		  <p>価格: <%= @product.price %>円</p>
		  <p>送料: <%= @product.delivery_fee %>円</p>
		  <p><%= link_to '特定商取引情報', dealer_info_market_path %></p>
		  <br>
		  <p>個数  <%= f.text_field :request_count %></p>
		
		  <label>お届け先名</label>
		  <%= f.text_field :name %>
		  <label>お届け先郵便番号</label>
		  <%= f.text_field :address_number %>
		  <label>お届け先</label>
		  <%= f.text_field :address %>
		  <label>ご連絡先(email)</label>
		  <%= f.text_field :user_email %>
		  <label>ご連絡先(電話番号)</label>
		  <%= f.text_field :user_tel %>
		
		  <%= f.submit %>
		<% end %>
	</div>
</div>

app/views/market/success.html.erb
<div class="market w2">
<div class="confirm">
<h1>お支払い先情報の確認</h1>

<table>
  <tr><td>支払先名 : </td><td><%= @address['name'] %></td></tr>
  <tr><td>支払先会社名 : </td><td><%= @address['company'] %></td></tr>
  <tr><td>住所 1 : </td><td><%= @address['address1'] %></td></tr>
  <tr><td>住所 2 : </td><td><%= @address['address2'] %></td></tr>
  <tr><td>市町村 : </td><td><%= @address['city'] %></td></tr>
  <tr><td>県 : </td><td><%= @address['state'] %></td></tr>
  <tr><td>国 : </td><td><%= @address['country'] %></td></tr>
  <tr><td>Zip</td><td><%= @address['zip'] %></td></tr>
</table>

<%= form_tag :action => 'complete', :token => params[:token], :payer_id => params[:PayerID] do %>
  <%= submit_tag 'Complete Payment' %>
<% end %>
</div>
</div>