config/routes.rb
Posfis::Application.routes.draw do
  
  namespace :manage do
    resources :friends do
      member do
        get 'add_friend'
      end
    end
    resources :products do
      collection do
        get 'dealerInfo'
      end
    end
    resources :blogs
    resources :trades do
      collection do
        get 'history'
      end
    end
    resources :orders do
      collection do
        get 'history'
      end
      member do
        get 'next_phase'
      end
    end
    resources :settings
    resources :user_settings
    resources :product_value
    resources :dealer_info
  end

  namespace :admin do
    resources :users
    resources :logs
  end

  root 'tops#index'

  devise_for :users, :controllers => { :registrations => :registrations }

  

  resources :tops
  resources :blogs

  resources :market do
    member do
      get 'purchase'
      post 'confirm'
      post 'checkout'
      get 'success'
      post 'complete'
      get 'dealer_info'
    end
  end

  namespace :manage do
  end
  resources :manage do
    collection do
      post 'create_blog'
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ActionController::Base
	layout 'tops'
	before_action :set_params, only: [:show]


	# ユーザページ
	def index
	end

	def show
		@blogs = Manage::Blog.where(:user_id => params[:id])
		friends = Manage::Friend.select("to_user_id").where(:from_user_id => params[:id])
    @friends = Manage::Friend.where(:to_user_id => friends)
    @products = Manage::Product.where(:user_id => params[:id])
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_params
      @User = User.find(params[:id])
    end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<div class="main">
	<h1>アカウントはありますか？</h1>
	<ol>
		<li><%= link_to('アカウントを持っています', new_user_session_path)  %></li>
		<li><%= link_to('新規に登録します', new_user_registration_path)  %></li>
	</ol>
</div>

app/views/tops/show.html.erb
<header>
	<h1><%= @User.user_name %></h1>
	<div class="hlink">
		<% if user_signed_in? %>
		  <p><%= link_to '管理ページへ', manage_index_path %></p>
		<% else %>
		  <p><%= link_to 'トップページへ', tops_path %></p>
		<% end  %>
	</div>
</header>

	<div class="contents">
		<div class="container menus">

			<div class="item w2">
				<div class="imgBox">
					<%= image_tag @User.avatar.url(:medium) %>
				</div>
				<nav>
					<div class="navBox">
						<ul>
							<li class="menu info c1">
								<a href="">
									<span class="icon icon-user"></span>
									<h2>情報</h2>
									<p>広島県広島市</p>
								</a>
							</li>
							<li class="menu goods c2">
								<span class="icon icon-bag"></span>
								<h2>販売</h2>
								<p><%= @products.count %>点</p>
							</li>
						</ul>
					</div>
					<div class="navBox">
						<ul>
							<li class="menu friends c3">
								<span class="icon icon-users"></span>
								<h2>友達</h2>
								<p><%= @friends.count %>人</p>
							</li>
							<li class="menu pictures c4">
								<span class="icon icon-picture"></span>
								<h2>写真</h2>
								<p>13枚</p>
							</li>
						</ul>
					</div>
				</nav>
			</div>

			<% @blogs.each do |blog| %>
				<div class="item w1 c1">
					<div class="imgBox">
						<%= image_tag blog.picture.url(:medium) %>
					</div>
					<div class="inner">
						<h2><%= blog.title %></h2>
						<p><%= format_date blog.created_at %></p>
						<p><%= blog.content %></p>
					</div>
					<%= link_to '続きを読む', blog_path(blog.id), :class => "more" %>
				</div>
			<% end %>

			<% @products.each do |product| %>
				<div class="item w1 c1">
					<div class="imgBox">
						<%= image_tag product.picture.url(:medium) %>
					</div>
					<div class="inner">
						<h2><%= product.product_name %></h2>
						<p><%= format_date product.created_at %></p>
						<p><%= product.contents %></p>
					</div>
					<%= link_to '購入する', purchase_market_path, :class => "more" %>
				</div>
			<% end %>

		</div>
	</div>