config/routes.rb
Posfis::Application.routes.draw do
  
  namespace :manage do
    resources :friends do
      member do
        get 'add_friend'
      end
    end
    resources :products do
      collection do
        get 'dealerInfo'
      end
    end
    resources :blogs
    resources :trades do
      collection do
        get 'history'
      end
    end
    resources :orders do
      collection do
        get 'history'
      end
      member do
        get 'next_phase'
      end
    end
    resources :settings
    resources :user_settings
    resources :product_value
    resources :dealer_info
  end

  namespace :admin do
    resources :users
    resources :logs
  end

  root 'tops#index'

  devise_for :users, :controllers => { :registrations => :registrations }

  

  resources :tops
  resources :blogs

  resources :market do
    member do
      get 'purchase'
      post 'confirm'
      post 'checkout'
      get 'success'
      post 'complete'
      get 'dealer_info'
    end
  end

  namespace :manage do
  end
  resources :manage do
    collection do
      post 'create_blog'
    end
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
	belongs_to :user ,:class_name => 'User', :foreign_key => 'for_user_id'
	belongs_to :log_type, :class_name => 'LogType', :foreign_key => 'log_type'
end

app/models/log_type.rb
class LogType < ActiveRecord::Base
end

app/controllers/admin/logs_controller.rb
class Admin::LogsController < AdminController
	before_action :set_log, only: [:show, :edit, :update, :destroy]

	def index
		@logs = Log.all
	end

	def new
		@users = User.all
		@log_types = LogType.all
		@log = Log.new
	end

	def edit
		@users = User.all
		@log_types = LogType.all
	end

	def create
		@log = Log.new(log_params)
		if @log.for_user_id == nil
			@log.for_user_id = 0
		end
		if @log.save
			redirect_to admin_logs_path
		else
			redirect_to new_admin_logs_path
		end
	end

	def update
		if @log.update(log_params)
			redirect_to admin_logs_path
		else
			redirect_to edit_admin_logs_path
		end
		
	end

	private
		def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:for_user_id, :log_type, :log_message)
    end

end

app/helpers/admin/logs_helper.rb
module Admin::LogsHelper
end

app/views/admin/logs/_form.html.erb
<%= form_for(@logs) do %>
<% end %>

app/views/admin/logs/edit.html.erb
<div class="item w3">
	<div class="artList">
		<h2 class="bar">ログ編集</h2>
		<div class="inner">
			<%= form_for @log, :url => {:action => 'update'} do |f|%>
				<label for="for_user_id">宛先</label>
				<% if @log.for_user_id = 0 %>
					全ユーザ
					<%= f.hidden_field :for_user_id %>
				<% else %>
					<%= f.collection_select :for_user_id, @users, :id, :user_name, :prompt => "全ユーザ" %>
				<% end %>
				<br>
				<label for="log_type">ログタイプ</label>
				<%= f.collection_select :log_type, @log_types, :id, :type_name %>
				<br>
				<label for="log_message">ログメッセージ</label>
				<%= f.text_area :log_message %>
				<br>
				<%= f.submit %>
			<% end %>					
		</div>
	</div>
</div>

app/views/admin/logs/index.html.erb
<div class="item w3">
	<div class="artList">
		<h2 class="bar">システムログ一覧</h2>
		<div class="inner">
			<%= link_to '新規メッセージ作成', new_admin_log_path %>
			<% @logs.each do |log| %>
				<% if log.for_user_id != 0 %>
					<%= log.user.user_name %>
				<% else %>
					全ユーザ
				<% end %>
				<br>
				<%= log.log_type.type_name %>
				<br>
				<%= log.log_message %>
				<br>

				<br>
			<% end %> 						
		</div>
	</div>
</div>

app/views/admin/logs/new.html.erb
<div class="item w3">
	<div class="artList quick">
		<h2 class="bar">新規ログ作成</h2>
		<div class="inner">
			<%= form_for @log, :url => {:action => 'create'} do |f|%>
				<label for="for_user_id">宛先</label>
				<%= f.collection_select :for_user_id, @users, :id, :user_name, :prompt => "全ユーザ" %>
				<br>
				<label for="log_type">ログタイプ</label>
				<%= f.collection_select :log_type, @log_types, :id, :type_name %>
				<br>
				<label for="log_message">ログメッセージ</label>
				<%= f.text_area :log_message %>
				<br>
				<%= f.submit %>
			<% end %>					
		</div>
	</div>
</div>