config/routes.rb
Posfis::Application.routes.draw do
  
  namespace :manage do
    resources :friends do
      member do
        get 'add_friend'
      end
    end
    resources :products do
      collection do
        get 'dealerInfo'
      end
    end
    resources :blogs
    resources :trades do
      collection do
        get 'history'
      end
    end
    resources :orders do
      collection do
        get 'history'
      end
      member do
        get 'next_phase'
      end
    end
    resources :settings
    resources :user_settings
    resources :product_value
    resources :dealer_info
  end

  namespace :admin do
    resources :users
    resources :logs
  end

  root 'tops#index'

  devise_for :users, :controllers => { :registrations => :registrations }

  

  resources :tops
  resources :blogs

  resources :market do
    member do
      get 'purchase'
      post 'confirm'
      post 'checkout'
      get 'success'
      post 'complete'
      get 'dealer_info'
    end
  end

  namespace :manage do
  end
  resources :manage do
    collection do
      post 'create_blog'
    end
  end
end

app/models/asct_info.rb
class AsctInfo < ActiveRecord::Base
	belongs_to :user
end

app/models/delivery_type.rb
class DeliveryType < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
	belongs_to :user ,:class_name => 'User', :foreign_key => 'for_user_id'
	belongs_to :log_type, :class_name => 'LogType', :foreign_key => 'log_type'
end

app/models/log_type.rb
class LogType < ActiveRecord::Base
end

app/models/manage.rb
module Manage
  def self.table_name_prefix
    'manage_'
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :buyer_user ,:class_name => 'User', :foreign_key => 'buyer_user_id'
  belongs_to :business_user ,:class_name => 'User', :foreign_key => 'business_user_id'
  belongs_to :product, :class_name => 'Manage::Product', :foreign_key => 'product_id'
  include PublicActivity::Model
end

app/models/orders.rb
class Orders < ActiveRecord::Base
	belongs_to :buyer_user ,:class_name => 'User', :foreign_key => 'buyer_user_id'
  belongs_to :business_user ,:class_name => 'User', :foreign_key => 'business_user_id'
  belongs_to :manage_product
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :manage_blogs

	has_many :manage_friends_asso, :class_name => 'Manage::Friend', :foreign_key => :from_user_id
  has_many :manage_friends, :through => :manage_friends_asso, :source => :to_user_id

  has_many :orders_asso, :class_name => 'Order', :foreign_key => :buyer_user_id
  has_many :orders, :through => :orders_asso, :source => :business_user_id

  belongs_to :asct_info

  has_attached_file :avatar, {
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png]
    },
    :default_url => "/assets/noimg.png"
  }
  
end

app/controllers/admin_controller.rb
class AdminController < ManageController

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def show
		@blog = Manage::Blog.find(params[:id])
		@user = User.find(@blog.user_id)
		friends = Manage::Friend.select("to_user_id").where(:from_user_id => @blog.user_id)
    @friends = Manage::Friend.where(:to_user_id => friends)
    @products = Manage::Product.where(:user_id => @blog.user_id)
	end
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
	layout 'manage'
	before_filter :authenticate_user!

	def index
		friends = Manage::Friend.select("to_user_id").where(:from_user_id => current_user.id)
    @manage_blogs = Manage::Blog.where(:user_id => friends).order("created_at DESC").take(5)
		@quick_blog = Manage::Blog.new
		@blog_categories = Manage::BlogCategories.all
		all_user_logs = Log.where(:for_user_id => 0).where_values.reduce(:and)
		current_user_logs = Log.where(:for_user_id => current_user.id).where_values.reduce(:and)
		@logs = Log.where(all_user_logs.or(current_user_logs)).limit(10)

		user_activities = PublicActivity::Activity.where(:owner_id => current_user).where_values.reduce(:and)
		user_friends_activities = PublicActivity::Activity.where(:owner_id => friends).where_values.reduce(:and)
		@activities = PublicActivity::Activity.order("created_at DESC").where(:owner_type => "User").where(user_activities.or(user_friends_activities)).limit(20)

	end

	def create_blog
		@manage_blog = Manage::Blog.new(manage_blog_params)
    @manage_blog.user_id = current_user.id
    @manage_blog.condition = 1
    @manage_blog.save
    redirect_to manage_index_path
	end

	private
    # Never trust parameters from the scary internet, only allow the white list through.
    def manage_blog_params
      params.require(:manage_blog).permit(:user_id, :category_id, :title, :content, :condition, :picture)
    end

    
end

app/controllers/tops_controller.rb
class TopsController < ActionController::Base
	layout 'tops'
	before_action :set_params, only: [:show]


	# ユーザページ
	def index
	end

	def show
		@blogs = Manage::Blog.where(:user_id => params[:id])
		friends = Manage::Friend.select("to_user_id").where(:from_user_id => params[:id])
    @friends = Manage::Friend.where(:to_user_id => friends)
    @products = Manage::Product.where(:user_id => params[:id])
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_params
      @User = User.find(params[:id])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/manage_helper.rb
module ManageHelper
	def format_date(date)
		p date.strftime("%Y年%m月%d日")
	end

	def format_user_type(user_type)
		if user_type == 4
			p "[システム管理者]"
		elsif user_type == 1
			p "[消費者]"
		elsif user_type == 2
			p "[生産者]"
		elsif user_type == 3
			p "[業者]"
		end
	end

	def log_message(log_type)
		if log_type == 0
			p "システムメンテナンス"
		elsif log_type == 1
			p "システムアップデート"
		end
	end	
end

app/helpers/market_helper.rb
module MarketHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Posfis</title>
  <!--[if IE]>
      <link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/manage.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">
  <title>admin | Farmer</title>
  <!--[if IE]>
      <link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <![endif]-->
  <%= stylesheet_link_tag    "manage", media: "all", "data-turbolinks-track" => true %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
  <%= javascript_include_tag "h-jquery-masonry.pkgd.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "imagesloaded", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "z-jquery.admin", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "z-jquery.farmer", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="hdrContents">
			<div class="logo">
				<h1>FIS</h1>
			</div>
			<div class="hdrTools">
				<span class="plus">+</span>
				<span class="minus">-</span>
				<%= format_user_type current_user.user_type %><%= current_user.user_name %>
				<span class="icon-comment"></span>
				<%= link_to destroy_user_session_path, :method => "delete" do %>
				    <span class="lo icon-off"></span>
				<% end %>
			</div>
		</div>
	</header>
	<div class="contents">
		<div class="container">
			<div class="item nav w1">
				
				<ul>
					<li class="menu">
						<%= link_to manage_index_path do %>
				    	<span class="icon icon-home"></span><span class="tag">ホーム</span>
						<% end %>
					</li>
					<li class="menu">
						<%= link_to "/tops/#{current_user.id}" do %>
				    	<span class="icon icon-home"></span><span class="tag">Webページへ</span>
				    <% end %>
					</li>
					<li class="menu">
						<%= link_to manage_friends_path do %>
				    	<span class="icon icon-users"></span><span class="tag">友達</span>
						<% end %>
					</li>
					<li class="menu">
						<%= link_to manage_blogs_path do %>
				    	<span class="icon icon-book-open"></span><span class="tag">記事管理</span>
						<% end %>
					</li>
					<li class="menu">
						<%= link_to manage_products_path do %>
				    	<span class="icon icon-tag"></span><span class="tag">商品管理</span>
						<% end %>
					</li>
					<% if current_user.user_type >= 2 %>
					<li class="menu">
						<%= link_to manage_orders_path do %>
				    	<span class="icon icon-bag"></span><span class="tag">販売管理</span>
						<% end %>
					</li>
					<% end %>
					<li class="menu">
						<%= link_to history_manage_orders_path do %>
				    	<span class="icon icon-bag"></span><span class="tag">買物履歴</span>
						<% end %>
					</li>
					<li class="menu">
						<%= link_to manage_settings_path do %>
				    	<span class="icon icon-cog"></span><span class="tag">基本設定</span>
						<% end %>
					</li>
					<li class="menu">
						<%= link_to edit_user_registration_path do %>
				    	<span class="icon icon-user"></span><span class="tag">ユーザ設定</span>
						<% end %>
					</li>
					<% if current_user.user_type == 4 %>
						<li class="menu">
							<%= link_to admin_users_path do %>
					    	<span class="icon icon-users"></span><span class="tag">ユーザ管理</span>
							<% end %>
						</li>
						<li class="menu">
							<%= link_to admin_logs_path do %>
					    	<span class="icon icon-users"></span><span class="tag">システムログ</span>
							<% end %>
						</li>
					<% end %>
				</ul>
				
			</div>
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/layouts/market.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Posfis</title>
  <!--[if IE]>
      <link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <![endif]-->
  <%= stylesheet_link_tag    "manage","data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "market","data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/layouts/tops.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Posfis</title>
  <!--[if IE]>
      <link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <![endif]-->
  <%= stylesheet_link_tag    "manage","data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "tops","data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/public_activity/manage_blog/_create.html.erb
<% if activity.trackable %>
<tr>
	<td class="face"><%= image_tag activity.trackable.picture.url(:medium) %></td>
	<td class="friendInfo">
		<p class="date"><%= format_date activity.created_at %></p>
		<h3 class="title">「<%= link_to activity.trackable.title, manage_blog_path(activity.trackable.id) %>」を投稿しました。</h3>
		<p class="writer"><%= activity.owner.user_name %></p>
	</td>
	<td class="shareItem">
		<ul>
		<li class="star"><span class="icon icon-star-empty"></span></li>
		<li><span class="icon icon-export"></span></li>
		</ul>
	</td> 
</tr>
<% end %>

app/views/public_activity/manage_blog/_update.html.erb
<% if activity.trackable %>
<tr>
	<td class="face"><%= image_tag activity.trackable.picture.url(:medium) %></td>
	<td class="friendInfo">
		<p class="date"><%= format_date activity.created_at %></p>
		<h3 class="title">「<%= link_to activity.trackable.title, manage_blog_path(activity.trackable.id) %>」の記事を更新しました。</h3>
		<p class="writer"><%= activity.owner.user_name %></p>
	</td>
	<td class="shareItem">
		<ul>
		<li class="star"><span class="icon icon-star-empty"></span></li>
		<li><span class="icon icon-export"></span></li>
		</ul>
	</td> 
</tr>
<% end %>

app/views/public_activity/manage_friend/_add_friend.html.erb
<% if activity.trackable %>
<tr>
	<td class="face"></td>
	<td class="friendInfo">
		<h3 class="title">
			<% if activity.owner.user_name != current_user.user_name %>
				<%= link_to activity.owner.user_name, top_path(activity.trackable.id) %>と<%= link_to User.find(p[:to_user]).user_name, top_path(User.find(p[:to_user]).id) %>が友達になりました。
			<% else %>
				<%= link_to User.find(p[:to_user]).user_name, top_path(User.find(p[:to_user]).id) %>と友達になりました。
			<% end %>
		</h3>
	</td>
	<td class="shareItem">
	</td> 
</tr>
<% end %>

app/views/public_activity/manage_friend/_destroy.html.erb
<% if activity.trackable %>
<% end %>

app/views/public_activity/manage_friend/_update.html.erb
<% if activity.trackable %>
<% end %>

app/views/public_activity/manage_product/_create.html.erb
<% if activity.trackable %>
<tr>
	<td class="face"><%= image_tag activity.trackable.picture.url(:medium) %></td>
	<td class="friendInfo">
		<p class="date"><%= format_date activity.created_at %></p>
		<h3 class="title">「<%= link_to activity.trackable.product_name, manage_product_path(activity.trackable.id) %>」の商品を登録しました。</h3>
		<p class="writer"><%= activity.owner.user_name %></p>
	</td>
	<td class="shareItem">
		<ul>
		<li class="star"><span class="icon icon-star-empty"></span></li>
		<li><span class="icon icon-export"></span></li>
		</ul>
	</td> 
</tr>
<% end %>

app/views/public_activity/manage_product/_update.html.erb
<% if activity.trackable %>
<tr>
	<td class="face"><%= image_tag activity.trackable.picture.url(:medium) %></td>
	<td class="friendInfo">
		<p class="date"><%= format_date activity.created_at %></p>
		<h3 class="title">「<%= link_to activity.trackable.product_name, manage_product_path(activity.trackable.id) %>」の商品を更新しました。</h3>
		<p class="writer"><%= activity.owner.user_name %></p>
	</td>
	<td class="shareItem">
		<ul>
		<li class="star"><span class="icon icon-star-empty"></span></li>
		<li><span class="icon icon-export"></span></li>
		</ul>
	</td> 
</tr>
<% end %>